version: '3.4'

services:
  tgapihttpproxy:
    image: tgapihttpproxy
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 127.0.0.1:3000:3000
